version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    #volumes:
    #  - /opt/homebrew/var/postgres:/var/lib/postgresql/data
    restart: always
    # environment variables for postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456.
    ports:
      - 5432:5432

  pythonapp:
    image: berkaydemirtas/data_crawler:v1
